name: Test Java with Maven

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      # Setup Chrome browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # Setup ChromeDriver
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'

      # Run tests cu -Dremote=true ca sa se foloseasca headless și inițializare corectă
      - name: Run Automation FinalTest
        run: mvn clean install -Dremote=true