name: Test Java with Maven

on:
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-common libnss3 libxss1 libappindicator3-1 libatk-bridge2.0-0 libgtk-3-0

      - name: Setup JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: maven

      - name: Download ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"
          LATEST_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Latest compatible ChromeDriver version: $LATEST_DRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/${LATEST_DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests with Maven
        env:
          DISPLAY: :99
        run: |
          # Start virtual framebuffer (Xvfb) in background
          Xvfb :99 -screen 0 1920x1080x24 &
          
          # Run Maven tests
          mvn clean test